config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :candidates, only: %i[index show new create update destroy] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index update edit]
  resources :reviews, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :candidate
  has_many :reviews

  validates :start_date, presence: true
  validates :end_date, presence: true

  # validates :start_date, format: { with: %r{[1-9]{1}[0-9]{1}/[0-9]{2}/[0-9]{4}} }

  # validates :start_date, date: { before: :end_date }
  validates :total_price, numericality: { only_integer: true }
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  # PARTIS = ["En Marche", "Les Républicains", "Debout la République", "Les Patriotes", "Cap écologie"]
  belongs_to :political_party
  belongs_to :user

  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  has_many :reviews, through: :bookings

  validates :first_name, :last_name, presence: true
  validates :price_per_day, presence: true, numericality: { only_integer: true }
  validates :description, length: { minimum: 5 }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/political_party.rb
class PoliticalParty < ApplicationRecord
  belongs_to :candidate, optional: true

  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :comment, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :candidates, dependent: :destroy
  has_many :bookings, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "only valid mail address" }
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!


end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # skip_before_action :authenticate_user!, only: :index
  # before_action :set_user, only: :new
  before_action :set_candidate, only: %i[create new]

  def index
    # my_current_user =
    @bookings = Booking.where(user_id: current_user.id).order(id: :desc)
    @review = Review.new
  end

  def new
    @booking = Booking.new
    #@review = Review.new
    @candidate = Candidate.find(params[:candidate_id])
  end

  def create
    @booking = Booking.new(booking_params)
    start_date = Date.parse(params[:booking][:start_date])
    end_date = Date.parse(params[:booking][:end_date])
    total_days = (end_date - start_date) + 1
    price_per_day = @candidate.price_per_day
    total_price = price_per_day * total_days
    total_price = total_price.to_i
    @booking.total_price = total_price
    @booking.user = current_user
    @booking.candidate = @candidate
    if @booking.save
      redirect_to bookings_path
    else
      render :show
    end
  end

  def destroy
  end

  private

  def set_candidate
    @candidate = Candidate.find(params[:candidate_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :total_price)
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  # skip_before_action :authenticate_user!, only: :index
  def index
    if params[:query].present?
      @query = params[:query]
      sql_query = " \
        candidates.last_name ILIKE :query \
        OR candidates.description ILIKE :query\
        OR candidates.first_name ILIKE :query \
        OR political_parties.name ILIKE :query \
      "
      @candidates = Candidate.joins(:political_party).where(sql_query, query: "%#{params[:query]}%")

    else
      @candidates = Candidate.where.not(latitude: nil, longitude: nil)
    end

    @markers = @candidates.map do |candidate|
      {
        lat: candidate.latitude,
        lng: candidate.longitude,
        info_window: render_to_string(partial: "info_window", locals: { candidate: candidate })
        # image_url: helpers.asset_url('REPLACE_THIS_WITH_YOUR_IMAGE_IN_ASSETS')
      }
    end
  end

  def show
    @candidate = Candidate.find(params[:id])
    @photo_main = @candidate.photos.find_by(blob_id: 1)
    @photo_thumb_1 = @candidate.photos.find_by(blob_id: 2)
    @photo_thumb_2 = @candidate.photos.find_by(blob_id: 3)
    @photo_thumb_3 = @candidate.photos.find_by(blob_id: 4)
    @photo_thumb_4 = @candidate.photos.find_by(blob_id: 5)
    political_party = PoliticalParty.find(@candidate.political_party_id)
    @logo = political_party.logo
    @booking = Booking.new
  end

  def new
    @candidate = Candidate.new
  end

  def create
    raise
    curr_user = User.find(29)
    @candidate = Candidate.new(candidates_params)
    @candidate.user = curr_user
    if @candidate.save
      redirect_to candidates_path
    else
      render :new
    end
  end

  private

  def candidates_params
    params.require(:candidate).permit(:first_name, :last_name, :description, :price_per_day, :political_party_id,
                                      photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    # @booking = Booking.find(params[:booking_id])
    # @candidate = Candidate.find(@booking.candidate_id)
    @review = Review.new
    raise
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:review][:id])
    @review.booking = @booking
    if @review.save
      redirect_to bookings_path
    else
      render "bookings/index"
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new_booking.html.erb
<div class="form-container">
      <div class="form-body">

          <div class="date-picker-left">
            <div>
              <%= f.input :start_date, as: :date, html5: true, label: 'DEBUT' %>
            </div>
          </div>

          <div class="date-picker-right">
            <div>
              <%= f.input :end_date, as: :date, html5: true, label: 'FIN' %>
            </div>
          </div>
      </div>
      <div class="bottom">
        <% unless @booking.total_price.nil? %>
          <span><p>Total : <%= @booking.total_price %> €</p></span>
        <% end %>
        <%= f.submit "VALIDER", class: "button" %>
      </div>
    <% end %>
    
</div>

app/views/bookings/index.html.erb
<div class="banner">
  <%= render "shared/navbar_home"%>
</div>
<div class="containerrecap">
  <h1> Récapitulatif de vos réservations</h1>
  <div class="container-table">
    <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">N°</th>
        <th scope="col">Du</th>
        <th scope="col">Au</th>
        <th scope="col">Montant</th>
        <th scope="col">Candidat</th>
        <th scope="col"></th>
        <th scope="col">Réservation</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody class="bck-color">
      <% @bookings.each do |booking|  %>
      <tr>
        <th scope="row"><%= booking.id %></th>
        <% @info_id = booking.id %>
        <% @info_img = booking.candidate.photos[0].key %>
        <% @info_first = booking.candidate.first_name %>
        <% @info_last = booking.candidate.last_name %>
        <td><%= booking.start_date.strftime("%d/%m/%Y") %></td>
        <td><%= booking.end_date.strftime("%d/%m/%Y") %></td>
        <td><%= booking.total_price %>€</td>
        <td><%= booking.candidate.first_name %> <%= booking.candidate.last_name %></td>
        <td><%= link_to (image_tag "ArrowSquareOut.png", width: 20, height: 20 ), candidate_path(booking.candidate)%></td>
        <% if booking.status %>
          <td><span class="bfinish">Confirmée<span></td>
        <% else %>
          <td><span class="brun">En cours</span></td>
        <% end %>
        <%# <td><%= link_to (image_tag "ChatCircleDots.png", width: 20, height: 20), new_booking_review_path(booking) %>
       <td><%= image_tag "ChatCircleDots.png", width: 20, height: 20, data: { toggle: "modal" , target: "#exampleModal#{@info_id}" }  %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

      <!-- Modal -->
      <div class="modal fade" id="exampleModal<%= @info_id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-contentt">

            <div class="modal-bodyy">

            <div class="container_review2">
              <div class="row">
                <div class="col-6 img_rev">
                  <%= cl_image_tag @info_img, width: 327, height: 338, class: "img_rev" %>
                </div>
                <div class="col-6 rev-txt">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
                  <p>Votre commentaire à <span><%= @info_first %> <%= @info_last%></span></p>
                  <%= simple_form_for @review do |f| %>
                    <%= f.input :comment ,label: " ", class: "space-form-review-comment"%>
                    <%= f.input :rating, collection: (1..5).to_a, label: "Note :", class: "space-form-review" %>
                    <%= f.input :id, :as => :hidden, input_html: { value: @info_id } %>
                    <%= f.submit "Envoyer le commentaire", class: "btn btn-primary w-100 txt-btn" %>
                  <% end %>
                </div>
              </div>
            </div>

            </div>
          </div>
        </div>
      </div>

app/views/bookings/new.html.erb
<div class="banner">
  <%= render "shared/navbar_home"%>
</div>


<div>
  <%= render "shared/footer" %>
</div>

app/views/candidates/_form_new_candidate.html.erb
<div class="banner">
  <%= render "shared/navbar_home"%>
</div>
<div class="container-card">
  <div class="container white-background">
  <div class="container">
    <h3 class="textcenter">Ajoutez un candidat</h3>
  </div>
  <div class="justify-content-md-center container">
    <%= simple_form_for @candidate do |f| %>
      <div class="container input-basic"><%= f.input :first_name, label: 'Prénom du candidat' %></div>
      <%= f.input :last_name, label: 'Nom du candidat' %>
      <%# <%= f.input :photos, label: 'Photo(s) 5 max.' %>
      <%= f.input :description %>
      <%= f.association :political_party, label: 'Parti politique' %>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>
      <%= f.input :price_per_day, label: 'Prix' %>
      <%= f.button :submit, class:"btn btn-outline-danger" %>
    <% end %>
  </div>
</div>
</div>
<h3><%= @user %></h3>

app/views/candidates/_info_window.html.erb
<%= cl_image_tag candidate.photos[0].key, class: "img-marker", alt: "Candiloc 2022", gravity: "faces" %>
<h2><%= candidate.first_name %> <%= candidate.last_name %> </h2>
<p><%= candidate.address %></p>
<p><%= candidate.political_party.slogan[0,40] %></p>

<p class="parti-prix"><%= candidate.price_per_day %>€ / Jour <%= image_tag candidate.political_party.logo, alt: "logo du parti politique", width: 57, height:29 %></p>

app/views/candidates/index.html copy.erb
<div class="banner">
  <%= render "shared/navbar_home"%>
  <div class="container">
    <h1 class="textcenter">Candidats disponibles à la location</h1>
  </div>
  <div class="">
    <form action="" class="container_form">
      <div class="input-groups mb-3">
        <span class="input-group-textl"><%= image_tag "logosearch.png", alt: "Candiloc 2022", width: 24, height: 24 %></span>
        <input type="search" class="form-controlm" name="query" value="<%= params[:query] %>" placeholder="Chercher un parti politique" >
        <span type="submit" class="input-group-textr">Search</span>
      </div>
    </form>
  </div>
</div>
<div class="container-card">
  <div class="bastien">
  <%= image_tag "frame_bastien.png", alt: "To do", width: 933, height: 36 %>
  </div>
    <div class="cards">
      <%# début du each %>
      <% @candidates.each do |candidate| %>
        <div class="one-card ">
          <%= link_to candidate_path(candidate) do %>
            <%= cl_image_tag candidate.photos[0].key, class: "card-imag-top", alt: "Candiloc 2022", width: 200, height: 200 %>
            <div class="one-card-body">
                <h5 class="one-card-title"><%= candidate.last_name %></h5>
                <h5 class="one-card-title"><%= candidate.first_name %></h5>
                <p class="one-card-text"><%= candidate.political_party.name %></p>
            </div>
            <div class="one-card-price">
              <p id="one-card-price-p"><%= candidate.price_per_day %>€ / J</p>
            </div>
          <% end %>
        </div>
        <%# fin du each %>
      <% end %>
    </div>

    <div id="map"
      style="width: 100%; height: 600px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    </div>
  </div>
</div>
<div>

</div>

app/views/candidates/index.html.erb
<div class="banner">
  <%= render "shared/navbar_home"%>
  <div class="container-b">
    <h1 class="textcenter">Candidats disponibles à la location</h1>
  </div>
  <div class="">
    <form action="" class="container_form">
      <div class="input-groups mb-3">
        <span class="input-group-textl"><%= image_tag "logosearch.png", alt: "Candiloc 2022", width: 24, height: 24 %></span>
        <input type="search" class="form-controlm" name="query" value="<%= params[:query] %>" placeholder="Vous recherchez : un candidat ? un parti politique ? une compétence ? " >
        <span type="submit" class="input-group-textr">C'est parti !</span>
      </div>
    </form>
  </div>
</div>
<div class="container-number-candidates">
  <% if @query %>
    <p>Vous avez recherché <strong>"<%= @query %>"</strong>. Nous avons trouvé <%= @candidates.count %> résultat(s).</p>
  <% else %>
    <p>Voici les <%= Candidate.count %> candidats disponibles.</p>
  <% end %>
  <div id="btswitch">
    <%= image_tag "toggleList.png",alt: "Candiloc 2022", id: "img-tgle-switch", width: 72, height:35, display: true %>
  </div>
</div>
<div  id="disp_card" class="container-card">
  <div  class="cards">
    <%# début du each %>
    <% @candidates.each do |candidate| %>
      <div class="one-card ">
        <%= link_to candidate_path(candidate) do %>
          <%= cl_image_tag candidate.photos[0].key, class: "card-imag-top", alt: "Candiloc 2022", width: 285, height:154, gravity: "faces"  %>
          <div class="one-card-logo">
            <%= image_tag candidate.political_party.logo, alt: "Candiloc 2022", width: 57, height:29 %>
          </div>
            <div class="one-card-body">
              <h5 class="one-card-title"><%= candidate.last_name %> <%= candidate.first_name %></h5>
              <p class="one-card-text"><%= candidate.political_party.slogan[0,40] %></p>
              <p class="one-card-text-data"><%= candidate.description[0,110] %>... <span>Lire plus</span></p>
            </div>

            <div class="one-card-price">
              <p class="one-card-price-p"><%= image_tag "Star.png", alt: "Candiloc 2022", width: 14, height: 14 %><%= candidate.score %></p>
              <p class="one-card-price-p"><%= candidate.price_per_day %>€ / J</p>
            </div>
        <% end %>
      </div>
      <%# fin du each %>
    <% end %>
  </div>
</div>

<div id="disp_list" class="container-card-list">
  <div class="card-inside">
    <div class="cards-list">
      <% @candidates.each do |candidate| %>
        <%= link_to candidate_path(candidate) do %>
          <div class="card-content">
            <%= cl_image_tag candidate.photos[0].key, class: "card-imag-list", alt: "Candiloc 2022", width: 232, height:200, gravity: "faces" %>
            <div class="card-txt">
              <div class="txt-top">
                <div class="header">
                  <h5 class="one-card-title"><%= candidate.last_name %> <%= candidate.first_name %></h5>
                  <p class="one-card-price-p"><%= candidate.price_per_day %>€ / Jour</p>
                </div>
                <p class="one-card-text"><%= candidate.political_party.slogan[0,40] %></p>
                <p class="one-card-text-data"><%= candidate.description[0,110] %>... <span>Lire plus</span></p>
              </div>
              <div class="txt-bottom">
                <div class="header">
                  <div class="star">
                    <p class="one-card-price-p"><%= image_tag "Star.png", alt: "Candiloc 2022", width: 14, height: 14 %></p>
                    <p><%= candidate.score %></p>
                  </div>
                  <%= image_tag candidate.political_party.logo, alt: "Candiloc 2022", width: 57, height:29 %>
                </div>
              </div>
            </div>
          </div>
          <hr style="margin-left:100px;margin-right:100px;opacity:0">
        <% end %>
      <% end %>
    </div>
  </div>
  <%# <div class="map"> %>
    <div id="map"
      style="width: 100%; height: 100vh;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <%# </div> %>
</div>
<div>
  <%= render "shared/footer"%>
</div>

app/views/candidates/new.html.erb
    <%= render "form_new_candidate", candidate: @candidate %>

app/views/candidates/show.html.erb
<div class="body">
  <div class="banner">
    <%= render "shared/navbar_home"%>
  </div>

    <div class="wrapper">

      <div class="main-show-card">
        <div class="show-card">
          <div class="intro-show-card">
            <div class="item-intro-show-card">
              <h2 id="title-show-card-h2"><%= @candidate.first_name %> <%= @candidate.last_name %></h2>
              <h3 id="title-show-card-h3"><%= @candidate.political_party.name %></h3>
            </div>
            <div class="item-intro-show-card-logo">
              <%= image_tag("large/#{@candidate.political_party.logo}", alt: "La republique en marche", width: 160, height:60) %>
            </div>
          </div>

          <div class="candidate-photo-grid">
            <%= cl_image_tag @candidate.photos[0].key, crop: "fill" %>
            <%= cl_image_tag @candidate.photos[1].key, crop: "fill", effect: "improve", gravity: "faces" %>
            <%= cl_image_tag @candidate.photos[2].key, crop: "fill", effect: "improve", gravity: "faces" %>
            <%= cl_image_tag @candidate.photos[3].key, effect: "improve", gravity: "faces" %>
            <%= cl_image_tag @candidate.photos[4].key, effect: "improve", gravity: "faces" %>
          </div>

        <div class="card-bottom-container">
          <div class="Stats">
            <div class="stats-img"><%=  image_tag "Star.png", height:30, width:30  %>
            <span class="stats-score"><%= @candidate.score %></span>
            </div>
            <div class="stats-price"><p>1000 €/J</p></div>
          </div>
          <div class="Comments">
          <div class="item-description-show-card">
          <h3>Description</h3>
            <p><%= @candidate.description %></p>
          </div>
           <%= image_tag 'flag_line.png', class: "img_flag"%>
            <h3>Commentaires</h3>
              <% @candidate.reviews.each do |review|  %>
              <div class="comment">
                <div class="comment-header">
                  <p id="user-name"><%= current_user.last_name %></p>
                  <p id="date-comment"><%= review.created_at.strftime("%d/%m/%Y") %></p>
                </div>
                <div class="comment-body">
                  <p id="comment-background"><%= review.comment %></p>
                </div>
              </div>
            <% end %>
          </div>
          <div class="sidebar">
            <h3>Reservez votre candidat</h3>
            <div class="date-pickr">
              <%= simple_form_for [ @candidate, @booking ] do |f| %>
                <%= f.input :start_date, placeholder: 'Ajoutez une date', label: "DATE DE DÉBUT", as: :string, input_html: { class: "datepicker"} %>
                <%= f.input :end_date, placeholder: 'Ajoutez une date', label: "DATE DE FIN",  as: :string, input_html: { class: "datepicker"} %>
                <%= f.submit "Reservez", class: 'btn btn-french' %>
              <% end  %>
            </div>
          </div>
        </div>


        </div> <!--show card -->
      </div>
    </div> <!-- wrapper -->

  <div class="show-footer">
    <%= render "shared/footer"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Candiloc</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet' />
  </head>

  <body>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
  <video id="background-video" autoplay loop muted >
    <source src="https://res.cloudinary.com/dusd899tr/video/upload/v1644676795/louvre_ex7r7l.mp4" type="video/mp4">
  </video>
  <%= render "shared/navbar_home"%>
  <div class="container-b text-center centr">
    <h1 class="title-home">Louez votre candidat préféré</h1>
    <%# <%= link_to "COMMENCER", candidates_path, class: "btn_enter text-center"  %>
  </div>
    <div class="center-search">
    <%= render "shared/search_b"%>
  </div>

</div>

app/views/pages/sign_in.html.erb
<div class="container">
  <div class="card">
    <div class="card-body rounded">
      <div class="card-block text-center">
        <h3>Inscrivez-vous</h3>
      </div>
      <div class="mb-3" class="form mt-3">
        <label for="exampleFormControlInput1" class="form-label">Prenom</label>
        <input type="email" class="form-control" id="exampleFormControlInput1">
        <label for="exampleFormControlInput1" class="form-label mt-3">Nom</label>
        <input type="email" class="form-control" id="exampleFormControlInput1">
        <label for="exampleFormControlInput1" class="form-label mt-3">Email</label>
        <input type="email" class="form-control" id="exampleFormControlInput1">
        <label for="exampleFormControlInput1" class="form-label mt-3">Mot de passe</label>
        <input type="email" class="form-control" id="exampleFormControlInput1">
      </div>
    <div class="card-block text-center">
      <button type="button" class="btn btn-primary mt-3 mb-3">S'inscrire</button>
      <p>Déjà compte? <span>Connectez-vous</span></p>
    </div>
    </div>
  </div>
</div>

app/views/reviews/_form_add_review.html.erb
<div class="container_review2">
  <div class="row">
    <div class="col-6 img_rev">
        <%# <%= cl_image_tag @candidate.photos[0].key, width: 327, height: 338, class: "img_rev" %>
    </div>
    <div class="col-6 rev-txt">
      <p>Votre commentaire à <span><span></p>
      <%= simple_form_for @review do |f| %>
        <%= f.input :comment ,label: " ", class: "space-form-review-comment"%>
        <%= f.input :rating, collection: (1..5).to_a, label: "Note :", class: "space-form-review" %>
        <%= f.submit "Envoyer le commentaire", class: "btn btn-primary w-100 txt-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="banner">
  <%= render "shared/navbar_home"%>
  <div>
    <%= render "form_add_review"%>
  </div>

</div>
  <%= render "shared/footer"%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#" id="first_i"><i class="fab fa-instagram"></i></a>
    <a href="#" id="second_i"><i class="fab fa-facebook"></i></a>
    <a href="#" id="third_i"><i class="fab fa-twitter"></i></a>
    <a href="#" class="wagont"><img class="wagont" src="https://kitt.lewagon.com/placeholder/users/pyveslg" width="30" height="30" alt=""></a>
    <a href="#" class="wagont"><img  class="wagont" src="https://kitt.lewagon.com/placeholder/users/alexisjps" width="30" height="30" alt=""></a>
    <a href="#" class="wagont"><img  class="wagont" src="https://kitt.lewagon.com/placeholder/users/Caaam333" width="30" height="30" alt=""></a>
    <a href="#" class="wagont"><img  class="wagont" src="https://kitt.lewagon.com/placeholder/users/Tetreur" width="30" height="30" alt=""></a>
    <a href="#" class="wagont"><img  class="wagont" src="https://kitt.lewagon.com/placeholder/users/medericmesle" width="30" height="30" alt=""></a>
    <a href="#" class="wagont"><img  class="wagont" src="https://kitt.lewagon.com/placeholder/users/christophe126" width="30" height="30" alt=""></a>
  </div>
  <div class="footer-text">
    <p>Le capitalisme <i class="far fa-money-bill-alt grrenn"></i> democratique est en marche.</p>
  </div>
</div>

app/views/shared/_search_b.html.erb
<div class="">
  <form action="candidates/" class="container_form">
    <div class="input-groups mb-3">
      <span class="input-group-textl"><%= image_tag "logosearch.png", alt: "Candiloc 2022", width: 24, height: 24 %></span>
      <input type="search" class="form-controlm" name="query" value="<%= params[:query] %>" placeholder="Vous recherchez un candidat ? un parti politique ? une compétence particulière ?" >
      <span type="submit" class="input-group-textr">C'est parti !</span>
    </div>
  </form>
</div>

app/views/users/new.html.erb
<div class="container">
<div class="card">
<div class="card-body rounded">
<div class="card-block text-center">
<h3>Connectez-vous</h3>
</div>
<div class="mb-3" class="form mt-3">
<label for="exampleFormControlInput1" class="form-label">Email</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="candidat@candiloc.com">
<label for="exampleFormControlInput1" class="form-label mt-3">Mot de Passe</label>
    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="C'est un secret">
</div>
<div class="card-block text-center">
<button type="button" class="btn btn-primary mt-3 mb-3">Se Connecter</button>
<p>Pas encore de compte? <span>Créer un compte</span></p>
</div>
</div>
</div>